#####################################################################################
##                                                                                 ##
##                                                                                 ##
##                            Home Assistant Configuration                         ##
##                                                                                 ##
##                                      Mark Bijker                                ##
##                                  mbijker84@gmail.com                            ##
##                                                                                 ##
##                                                                                 ##
#####################################################################################

####################################
##                                ##
## Basic information              ##
##                                ##
####################################
homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 0
  unit_system: metric
  time_zone: Europe/Amsterdam
  packages: !include_dir_named packages

frontend:
config:
http:
  base_url: !secret base_url
  api_password: !secret http_password
  ip_ban_enabled: True
  login_attempts_threshold: 3

updater:
discovery:
conversation:
history:
logbook:
map:
sun:
#cloud:

####################################
##                                ##
## iFrames                        ##
##                                ##
####################################
panel_iframe:
# nodered:
#   title: 'Node-Red'
#   icon: 'mdi:shuffle-variant'
#   url: !secret nodered_url
  dashboard:
    title: 'HA Dashboard'
    url: !secret dash_url
    icon: 'mdi:view-dashboard'

####################################
##                                ##
## Components                     ##
##                                ##
####################################
mqtt:
  broker: !secret mqtt_broker_ip
  username: !secret mqtt_broker_username
  password: !secret mqtt_broker_password

duckdns:
  domain: !secret duckdns_domain
  access_token: !secret duckdns_token
     
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chatid

notify:
  - name: telegram
    platform: telegram
    api_key: !secret telegram_api_key
    chat_id: !secret telegram_chatid 

####################################
##                                ##
## Includes                       ##
##                                ##
####################################
group: !include groups.yaml
#automation: !include_dir_merge_list automations/
script: !include scripts.yaml
