automation:
  - alias: Miranda thuis
    hide_entity: true
    initial_state: off
    trigger:
      platform: state
      entity_id: boolean.notification_telegram
      from: 'off'
      to: 'on'
 #       entity_id: device_tracker.miran000siphone
 #       from: 'not_home'
 #       to: 'home'
 #       for:
 #         minutes: 2
    condition:
      - platform: state
        entity_id: boolean.notification_telegram
        state: true
    action:
      service: notify.notify
      data:
        message: Test