automation:
  
  - alias: Miranda thuis
    hide_entity: true
    initial_state: on
    
    trigger:
      - platform: state
        entity_id: 
          - device_tracker.miran000siphone
          - device_tracker.samsunggalaxys7edge
        from: 'not_home'
        to: 'home'
        for: '00:02:00'

#    condition:
#      condition: state
#        entity_id: boolean.notification_telegram
#        state: true
    
    action:
      service: telegram_bot.send_message
      data_template:
        message: Miranda is thuisgekomen

#  - alias: Mark thuis
#    hide_entity: true
#    initial_state: on
#    trigger:
#      platform: state
#      entity_id: device_tracker.samsunggalaxys7edge
#      from: 'not_home'
#      to: 'home'
##        for:
##          minutes: 2
#    condition:
#      condition: state
#        entity_id: boolean.notification_telegram
#        state: true
#    action:
#      service: telegram_bot.send_message
#      data:
#        message: Mark is thuisgekomen