######################################################
# @author       :   Mark Bijker
# @package      :   Alarm
# @description  :   Control home alarm
######################################################


######################################################
## Base and customisations
######################################################
homeassistant:
  
  customize:
    

######################################################
## Components
######################################################
switch:
  - platform: mqtt
    state_topic:   "homeassistant/sensor/schuur/alarm"
    command_topic: "homeassistant/sensor/schuur/alarm"
    payload_on: "ON"
    payload_off: "OFF"
######################################################
## Boolean
######################################################
input_boolean:

######################################################
## Groups
######################################################
group:

######################################################
## Automations
######################################################
automation: