######################################################
# @author       :   Mark Bijker
# @package      :   Alarm
# @description  :   Control home alarm
######################################################


######################################################
## Base and customisations
######################################################
homeassistant:
  
  customize:
    switch.alarm_shed:
      friendly_name: Alarm schuur

######################################################
## Components
######################################################
switch:
  - platform: mqtt
    name: alarm_shed
    state_topic:   "homeassistant/sensor/schuur/alarm"
    command_topic: "homeassistant/sensor/schuur/alarm"
    payload_on: "ON"
    payload_off: "OFF"
######################################################
## Boolean
######################################################
input_boolean:

######################################################
## Groups
######################################################
group:

######################################################
## Automations
######################################################
automation:
  - alias: Alarm when away
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0002270299
      to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.awaymode
        state: 'on'
      - condition: state
        entity_id: input_boolean.guestmode
        state: 'off'
    action:
      - service: script.turn_on
        entity_id: script.alarm


######################################################
## Script
######################################################