######################################################
# @author       :   Mark Bijker
# @package      :   automations
# @description  :   Switches for automations
######################################################


######################################################
## Base and customisations
######################################################
homeassistant:
  
  customize:
    group.automations:
      friendly_name: Automatiseringen
      control: hidden
    

######################################################
## Components
######################################################

######################################################
## Boolean
######################################################
input_boolean:
  all_off_away:

######################################################
## Groups
######################################################
group:
  automations:
    entities:
      - input_boolean.guestmode
      - input_boolean.all_off_away
 
######################################################
## Automations
######################################################
automation:
  - alias: 'Set theme at startup'
    initial_state: 'on'
    trigger:
     - platform: homeassistant
       event: start
    action:
      service: frontend.set_theme
      data:
        name: dark