######################################################
# @author       :   Mark Bijker
# @package      :   automations
# @description  :   Switches for automations
######################################################


######################################################
## Base and customisations
######################################################
homeassistant:
  
  customize:
    group.automations:
      friendly_name: Automatiseringen
      control: hidden
    

######################################################
## Components
######################################################

######################################################
## Boolean
######################################################
input_boolean:

######################################################
## Groups
######################################################
group:
  automations:
    entities:
      - input_boolean.guestmode
      - input_boolean.lights_off_away
      - input_boolean.remote_off_away

######################################################
## Automations
######################################################
automation:
