homeassistant:
  customize:
    group.camera:
      order: 5
      friendly_name: "Bewakingscamera's"

camera:
  - platform: ffmpeg
    input: !secret camera1
    name: Tuin
  - platform: ffmpeg
    input: !secret camera2
    name: Steeg 1
  - platform: ffmpeg
    input: !secret camera3
    name: Steeg 2

group:
  cctv:
    entities:
      - camera.steeg_1
      - camera.steeg_2
      - camera.tuin