######################################################
# @author       :   Mark Bijker
# @package      :   darksky
# @description  :   Darksky weather
######################################################

######################################################
## Base and customisations
######################################################
homeassistant:
  
  customize:
    

######################################################
## Components
######################################################
sensor:
  platform: darksky
  api_key: !secret dark_sky_api
  units: si
  language: nl
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - temperature
    - humidity
    - precip_probability
    - precip_intensity
    - wind_speed
    - pressure
    - wind_bearing
    - apparent_temperature
    - cloud_cover
    - visibility
    - hourly_summary
    - daily_summary
    - temperature_max
    - temperature_min

######################################################
## Boolean
######################################################
input_boolean:

######################################################
## Groups
######################################################
group:
  weather:
    entities:
      - sensor.dark_sky_apparent_temperature
      - sensor.dark_sky_cloud_coverage
      - sensor.dark_sky_daily_high_temperature
      - sensor.dark_sky_daily_low_temperature
      - sensor.dark_sky_daily_summary
      - sensor.dark_sky_hourly_summary 
      - sensor.dark_sky_humidity
      - sensor.dark_sky_icon
      - sensor.dark_sky_nearest_storm_distance
      - sensor.dark_sky_precip_intensity
      - sensor.dark_sky_precip_probability
      - sensor.dark_sky_pressure
      - sensor.dark_sky_summary
      - sensor.dark_sky_temperature
      - sensor.dark_sky_visibility
      - sensor.dark_sky_wind_bearing
      - sensor.dark_sky_wind_speed
      
######################################################
## Automations
######################################################
automation:
