homeassistant:
  customize:
    group.miranda:
      friendly_name: Telefoon Miranda
      entity_picture: /local/images/gravatar_miranda.jpg
    group.family:
      order: 1
      friendly_name: Gezin
    group.network_devices:
      order: 2
      friendly_name: Netwerk devices

    device_tracker.mbijker_s7mark:
      friendly_name: Mark
    device_tracker.miran000siphone:
      friendly_name: Miranda
    device_tracker.bedlamp_mark1507_2:
      friendly_name: Bedlamp (Sonoff) Mark
      icon: mdi:lightbulb
    device_tracker.cctv:
      friendly_name: Bewakingscamera's
      icon: mdi:cctv
    device_tracker.chromecast:
      friendly_name: Chromecast huiskamer
      icon: mdi:cast
    device_tracker.esp_35ce56:
      friendly_name: Sensor Box Schuur
      icon: mdi:contrast-box
    device_tracker.harmonyhub_2:
      friendly_name: Harmony hub
      icon: mdi:remote
    device_tracker.iphone:
      friendly_name: Telefoon Xander
      hidden: true
      icon: mdi:cellphone-iphone
    device_tracker.laptopr44rsn95:
      friendly_name: Laptop Mark
      icon: mdi:laptop
    device_tracker.mbijker_s7mark:
      friendly_name: Telefoon Mark (owntracks)
    device_tracker.miran000siphone:
      friendly_name: Telefoon Miranda
    device_tracker.plafondlamp_slaapkamer6134_2:
      friendly_name: Plafondlamp slaapkamer (Sonoff)
      icon: mdi:lightbulb
    device_tracker.raspberrypi:
      friendly_name: HA Server
      icon: mdi:server
    device_tracker.re200:
      friendly_name: Wifi Repeater
      icon: mdi:wifi
    device_tracker.samsunggalaxys7edge:
      friendly_name: Telefoon Mark
    device_tracker.sonoff0614:
      friendly_name: Verlichting schuur (Sonoff)
      icon: mdi:lightbulb
    device_tracker.switch:
      friendly_name: Netwerk switch
      icon: mdi:switch
    device_tracker.thuis:
      friendly_name: Hue bridge
      icon: mdi:switch
    input_boolean.notify_everyone_away:
      friendly_name: Melding als iedereen weg is
      icon: mdi:bell
    input_boolean.notify_offline_device:
      friendly_name: Melding als netwerk apparaat wegvalt
      icon: mdi:bell
    input_boolean.guestmode:
      friendly_name: Gastmodus
      icon: mdi:account

input_boolean:
  notify_everyone_away:
    initial: on
  notify_offline_device:
    initial: on
  guestmode:
    initial: off

device_tracker:
  - platform: asuswrt
    host: !secret ip_router
    username: !secret router_username
    password: !secret router_password
  - platform: owntracks
    mqtt_topic: owntracks/#
    waypoints: True

group:
  
  miranda:
    control: hidden
    entities:
      - device_tracker.miran000siphone
      - device_tracker.miran000siphone_2
  
  family:
    control: hidden
    entities:
      - group.miranda
      - device_tracker.mbijker_s7mark
#      - input_boolean.notify_everyone_away
#      - input_boolean.guestmode
  
  network_devices:
    control: hidden
    entities:
      - device_tracker.bedlamp_mark1507_2
      - device_tracker.cctv
      - device_tracker.chromecast
      - device_tracker.esp_35ce56
      - device_tracker.harmonyhub_2
      - device_tracker.iphone
      - device_tracker.laptopr44rsn95
      - device_tracker.plafondlamp_slaapkamer6134_2
      - device_tracker.raspberrypi
      - device_tracker.re200
      - device_tracker.sonoff0614
      - device_tracker.switch
      - device_tracker.thuis
      - input_boolean.notify_offline_device

#automation:
#  - alias: miranda thuis
#    trigger:
#      platform: state
#      entity_id: group.miranda
#      to: 'home'
#      for:
#        minutes: 2
#    action:
#      service: notify.telegram
#      data:
#        message: Miranda is thuis

#  - alias: notify when everyone is away
#    trigger:
#      platform: state
#      entity_id: group.family
#      to: 'not_home'
#      for:
#        minutes: 1
#    condition:
#      - condition: state
#        entity_id: input_boolean.notify_everyone_away
#        state: on
#    action:
#      - service: notify.telegram
#        data:
#          message: Niemand thuis
#
#  - alias: lights off when everyone is away
#    trigger:
#      platform: state
#      entity_id: group.family
#      to: 'not_home'
#      for:
#        minutes: 1
#    condition:
#      condition: and
#      conditions:
#        - condition: state
#          entity_id: input_boolean.lights_off_away
#          state: on
#        - condition: state
#          entity_id: group.lights_card
#          state: on
#    action:
#      - service: notify.telegram
#        data:
#          message: Verlichting uitgedaan.
#      - service: light.turn_off
