######################################################
## Base and customisations                          ##
######################################################
homeassistant:
  customize:
    group.home:
      icon: mdi:home

######################################################
## Components                                       ##
######################################################

######################################################
## Boolean                                          ##
######################################################
input_boolean:

######################################################
## Groups                                           ##
######################################################
group:
  home:
    name: home
    view: yes
    entities:
      - group.family
      - group.lights_card
      - group.network_devices
      - group.remote_card
      - group.cctv
      - group.motion
      - group.time
      - group.humidity
      - group.temperature
      - group.battery

######################################################
## Automations                                      ##
######################################################
automation: