######################################################
# @author       :   Mark Bijker
# @package      :   Groups
# @description  :   Manage view groups
######################################################


######################################################
## Base and customisations
######################################################
homeassistant:
  customize:
    group.default_view:
      icon: mdi:home
######################################################
## Components
######################################################

######################################################
## Boolean
######################################################
input_boolean:

######################################################
## Groups
######################################################
group:
  default_view1:
    view: yes
    entities:
      - group.family
      - group.lights_card
      - group.network_devices
      - group.remote_card
      - group.cctv
      - group.motion
      - group.time
      - group.humidity
      - group.temperature
      - group.battery
      - group.performance
      - group.iss
      - group.weather
      - group.notify
      - group.automations
      - group.media_players
      - group.solar
      - group.printer
  lights:
    view: yes
    entities:
      - group.lights_card
  media:
    view: yes
    entities:
      - group.media_players
  statistics:
    view: yes
    entities:
      - group.network_devices
      - group.motion
      - group.time
      - group.humidity
      - group.temperature
      - group.battery
      - group.performance
      - group.weather
      - group.notify
      - group.automations
      - group.solar
      - group.printer
######################################################
## Automations
######################################################
automation: