######################################################
# @author       :   Mark Bijker
# @package      :   Humity
# @description  :   All humidity sensors
######################################################


######################################################
## Base and customisations
######################################################
homeassistant:
  customize:
    group.humidity:
      friendly_name: Luchtvochtigheid
    sensor.humidity_shed:
      friendly_name: Schuur
      icon: mdi:water-percent

######################################################
## Components
######################################################
sensor:
  - platform: mqtt
    state_topic: "homeassistant/sensor/schuur/humidity"
    unit_of_measurement: "%"
    name: humidity_shed

######################################################
## Boolean
######################################################
input_boolean:

######################################################
## Groups
######################################################
group:
  humidity:
    entities: sensor.humidity_shed

######################################################
## Automations
######################################################
automation: