####################################
##                                ##
## Lights                         ##
##                                ##
####################################

homeassistant:
  customize:
    group.lights_card:
      order: 3
    light.lights_shed:
      friendly_name: LED strips schuur
    light.bedlamp:
      friendly_name: Bedlamp Mark (HUE)
    light.slaapkamer:
      hidden: true
    light.woonkamer:
      hidden: true
    light.bedlight_mark:
      friendly_name: Bedlamp Mark
    light.bedlight_miranda:
      friendly_name: Bedlamp Miranda
    light.ceilinglight_master_bedroom:
      friendly_name: Plafondlamp Master bedroom
    input_boolean.lights_off_away:
      friendly_name: Verlichting uit als iedereen weg is

group:
  lights_card:
    name: Verlichting
    control: hidden
    entities:
      - light.bedlamp
      - light.bedlight_mark
      - light.bedlight_miranda
      - light.ceilinglight_master_bedroom
      - light.lights_shed
      - light.plafondlamp
      - input_boolean.lights_off_away

light:
  - platform: mqtt
    name: "lights shed"
    state_topic:   "homeassistant/switch/stat/sonoff/POWER"
    command_topic: "homeassistant/switch/cmnd/sonoff/POWER"
    payload_on: "ON"
    payload_off: "OFF"
  - platform: mqtt
    name: "bedlight mark"
    state_topic:   "homeassistant/switch/stat/bedlamp_mark/POWER"
    command_topic: "homeassistant/switch/cmnd/bedlamp_mark/POWER"
    payload_on: "ON"
    payload_off: "OFF"
  - platform: mqtt
    name: "bedlight miranda"
    state_topic:   "homeassistant/switch/stat/bedlamp_miranda/POWER"
    command_topic: "homeassistant/switch/cmnd/bedlamp_miranda/POWER"
    payload_on: "ON"
    payload_off: "OFF"
  - platform: mqtt
    name: "ceilinglight_master_bedroom"
    state_topic:   "homeassistant/switch/stat/plafondlamp_slaapkamer/POWER"
    command_topic: "homeassistant/switch/cmnd/plafondlamp_slaapkamer/POWER"
    payload_on: "ON"
    payload_off: "OFF"

input_boolean:
  lights_off_away:
    name: 'lights off nobody home'
    initial: on
    icon: mdi:lightbulb