######################################################
# @author       :   Mark Bijker
# @package      :   Lights
# @description  :   All lights
######################################################


######################################################
## Base and customisations
######################################################
homeassistant:
  customize:
    group.lights_card:
      order: 3
    light.lights_shed:
      friendly_name: LED strips schuur
    light.bedlamp:
      friendly_name: Bedlamp Mark (HUE)
    light.slaapkamer:
      hidden: true
    light.woonkamer:
      hidden: true
    light.bedlight_mark:
      friendly_name: Bedlamp Mark
    light.bedlight_miranda:
      friendly_name: Bedlamp Miranda
    light.ceilinglight_master_bedroom:
      friendly_name: Plafondlamp Master bedroom    

######################################################
## Components
######################################################
light:
  - platform: mqtt
    name: "lights shed"
    state_topic:   "homeassistant/switch/stat/sonoff/POWER"
    command_topic: "homeassistant/switch/cmnd/sonoff/POWER"
    payload_on: "ON"
    payload_off: "OFF"
  - platform: mqtt
    name: "bedlight mark"
    state_topic:   "homeassistant/switch/stat/bedlamp_mark/POWER"
    command_topic: "homeassistant/switch/cmnd/bedlamp_mark/POWER"
    payload_on: "ON"
    payload_off: "OFF"
  - platform: mqtt
    name: "bedlight miranda"
    state_topic:   "homeassistant/switch/stat/bedlamp_miranda/POWER"
    command_topic: "homeassistant/switch/cmnd/bedlamp_miranda/POWER"
    payload_on: "ON"
    payload_off: "OFF"
  - platform: mqtt
    name: "ceilinglight_master_bedroom"
    state_topic:   "homeassistant/switch/stat/plafondlamp_slaapkamer/POWER"
    command_topic: "homeassistant/switch/cmnd/plafondlamp_slaapkamer/POWER"
    payload_on: "ON"
    payload_off: "OFF"

######################################################
## Boolean
######################################################
input_boolean:

######################################################
## Groups
######################################################
group:
  lights_card:
    name: Verlichting
    control: hidden
    entities:
      - light.bedlamp
      - light.bedlight_mark
      - light.bedlight_miranda
      - light.ceilinglight_master_bedroom
      - light.lights_shed
      - light.plafondlamp

######################################################
## Automations
######################################################
automation:
  - alias: bedlight on
    trigger:
      platform: state
      entity_id: light.bedlight_mark
      to: 'on'
    action:
      service: light.turn_on
      entity_id: light.bedlamp

  - alias: bedlight off
    trigger:
      platform: state
      entity_id: light.bedlight_mark
      to: 'off'
    action:
      service: light.turn_off
      entity_id: light.bedlamp
#      data: 
#       - transition: 30