######################################################
# @author       :   Mark Bijker
# @package      :   Lights
# @description  :   All lights
######################################################


######################################################
## Base and customisations
######################################################
homeassistant:
  customize:
    group.lights_card:
      order: 3
    light.lights_shed:
      friendly_name: LED strips schuur
    light.bedlamp:
      friendly_name: Bedlamp Mark (HUE)
    light.slaapkamer:
      hidden: true
    light.woonkamer:
      hidden: true
    light.bedlight_mark:
      friendly_name: Bedlamp Mark
    light.bedlight_miranda:
      friendly_name: Bedlamp Miranda
    light.ceilinglight_master_bedroom:
      friendly_name: Plafondlamp Master bedroom    
    input_boolean.lights_off_away:
      friendly_name: Verlichting uit als iedereen weg is
      icon: mdi:lightbulb
    input_boolean.light_on_coming_home:
      friendly_name: Verlichting aan bij thuiskomen
      icon: mdi:lightbulb
    input_boolean.light_off_night:
      friendly_name: Verlichting uit bij nacht.
      icon: mdi:lightbulb

######################################################
## Components
######################################################
light:
  - platform: mqtt
    name: "lights shed"
    state_topic:   "homeassistant/switch/stat/sonoff/POWER1"
    command_topic: "homeassistant/switch/cmnd/sonoff/POWER1"
    payload_on: "ON"
    payload_off: "OFF"
  - platform: mqtt
    name: "bedlight mark"
    state_topic:   "homeassistant/switch/stat/bedlamp_mark/POWER1"
    command_topic: "homeassistant/switch/cmnd/bedlamp_mark/POWER1"
    payload_on: "ON"
    payload_off: "OFF"
  - platform: mqtt
    name: "bedlight miranda"
    state_topic:   "homeassistant/switch/stat/bedlamp_miranda/POWER1"
    command_topic: "homeassistant/switch/cmnd/bedlamp_miranda/POWER1"
    payload_on: "ON"
    payload_off: "OFF"
  - platform: mqtt
    name: "ceilinglight_master_bedroom"
    state_topic:   "homeassistant/switch/stat/plafondlamp_slaapkamer/POWER1"
    command_topic: "homeassistant/switch/cmnd/plafondlamp_slaapkamer/POWER1"
    payload_on: "ON"
    payload_off: "OFF"

#switch:
#  - platform: xiaomi_miio
#    name: lights_shed
#    host: 192.168.1.134
#    token: c4db09877c380c475e71b7ed1fcb6538
#    model: chuangmi.plug.m1

######################################################
## Boolean
######################################################
input_boolean:
  light_on_coming_home:
  light_off_night:
  
######################################################
## Groups
######################################################
group:
  lights_card:
    name: Verlichting
#    control: hidden
    entities:
      - light.bedlamp
      - light.bedlight_mark
      - light.bedlight_miranda
      - light.ceilinglight_master_bedroom
      - light.lights_shed
      - light.plafondlamp
      - light.gateway_light_7811dce13522
      - light.hue_color_lamp_1

######################################################
## Automations
######################################################
automation:
  - alias: bedlight on
    trigger:
      platform: state
      entity_id: light.bedlight_mark
      to: 'on'
    action:
      service: light.turn_on
      entity_id: light.bedlamp
      data_template:
        color_name: >
          {% if states.sensor.time.state < '06:00' %}
            {% if states.sensor.time.state > '00:00' %}
              red
            {% endif %}
          {% else %}
            orange
          {% endif %}
        brightness: >
          {% if states.sensor.time.state < '06:00' %}
            {% if states.sensor.time.state > '00:00' %}
              150
            {% endif %}
          {% else %}
            255
          {% endif %}

  - alias: bedlight off
    trigger:
      platform: state
      entity_id: light.bedlight_mark
      to: 'off'
    action:
      service: light.turn_off
      entity_id: light.bedlamp
      data:
        transition: 30


  - alias: turn on light on sunset when home
    trigger:
      platform: sun
      event: sunset
      offset: "-00:20:00"

    condition:
      - condition: state
        entity_id: group.family
        state: 'home'
#      - condition: state
#        entity_id: light.plafondlamp
#        state: 'off'

    action: 
      - service: scene.turn_on
        entity_id: scene.living_random
      - service: script.speech_main_logic
        data_template:
          message: "Het wordt al bijna donker. Ik zal de verlichting inschakelen."

  - alias: turn on light on coming home
    trigger:
      platform: state
      entity_id: group.family
      from: 'not_home'
      to: 'home'
    
    condition:
      - condition: state
        entity_id: input_boolean.light_on_coming_home
        state: 'on'
 #     - condition: state
 #       entity_id: light.plafondlamp
 #       state: 'off'
      - condition: state
        entity_id: sun.sun
        state: 'below_horizon'

    action:
      - service: scene.turn_on
        entity_id: scene.living_red
        data:
          color_name: orange
          brightness: 190
      - service: script.speech_main_logic
        data_template:
          message: "Welkom thuis. Ik zet de verlichting aan."

  - alias: turn off light when at night
    trigger:
      platform: time
      at: '23:59:00'

    condition:
      - condition: state
        entity_id: input_boolean.light_off_night
        state: 'on'
      - condition: state
        entity_id: group.family
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.guestmode
        state: 'off'

    action:
      - service: light.turn_off
        entity_id: group.all_lights
      - service: script.notify_me
        data_template:
          message: "Ik schakel de verlihting uit. Er is niemand thuis."

######################################################
## Scripts
######################################################

script:
  color_bedroom_red:
    sequence:
      - service: light.turn_on
        data:
          color_name: red
          entity_id: light.bedlamp
  color_bedroom_orange:
    sequence:
      - service: light.turn_on
        data:
          color_name: orange
          entity_id: light.bedlamp
  color_bedroom_white:
    sequence:
      - service: light.turn_on
        data:
          color_name: white
          entity_id: light.bedlamp
  color_bedroom_blue:
    sequence:
      - service: light.turn_on
        data:
          color_name: blue
          entity_id: light.bedlamp
  color_bedroom_purple:
    sequence:
      - service: light.turn_on
        data:
          color_name: purple
          entity_id: light.bedlamp
