######################################################
# @author       :   Mark Bijker
# @package      :   Media
# @description  :   All media players
######################################################


######################################################
## Base and customisations
######################################################
homeassistant:
  
  customize:
    group.media_players:
      friendly_name: Media spelers
    

######################################################
## Components
######################################################
media_player:
  - platform: snapcast
    host: 192.168.1.2
  - platform: gstreamer
    name: gstreamer
    pipeline: "audioresample ! audioconvert ! audio/x-raw,rate=48000,channels=2,format=S16LE ! wavenc ! filesink location=/tmp/snapfifo"
  - platform: mpd
    host: 192.168.1.2
######################################################
## Boolean
######################################################
input_boolean:

######################################################
## Groups
######################################################
group:
  media_players:
    entities:
      - media_player.mpd
      - media_player.gstreamer

######################################################
## Automations
######################################################
automation: