######################################################
# @author       :   Mark Bijker
# @package      :   Media
# @description  :   All media players
######################################################


######################################################
## Base and customisations
######################################################
homeassistant:
  
  customize:
    group.media_players:
      friendly_name: Media spelers
    

######################################################
## Components
######################################################
remote:
  - platform: harmony
    name: Living
    host: 192.168.1.25

tts:
  - platform: amazon_polly
    aws_access_key_id: !secret polly_access_key_id
    aws_secret_access_key: !secret polly_adccess_key
#    profile_name: HomeAssistant
#    region_name: 'nl'
    voice: Ruben
    text_type: ssml
  - platform: google

media_player:
  - platform: snapcast
    host: 192.168.1.2
  - platform: gstreamer
    name: gstreamer
    pipeline: "audioresample ! audioconvert ! audio/x-raw,rate=48000,channels=2,format=S16LE ! wavenc ! filesink location=/tmp/snapfifo"
  - platform: mpd
    host: 192.168.1.2

cast:
  media_player:
    - host: 192.168.1.21
    - host: 192.168.1.22
######################################################
## Boolean
######################################################
input_boolean:
  play_living:
  play_phone:

######################################################
## Input Select
######################################################
input_select:
  remote:
    name: Harmony remote
    options:
      - Uit
      - TV kijken
      - Chromecast kijken
      - Radio luisteren
      - Playstation spelen
      - Wii spelen
    icon: mdi:remote
######################################################
## Groups
######################################################
group:
  media_players:
    entities:
      - media_player.mpd
      - media_player.gstreamer

######################################################
## Scripts
######################################################
script:
  input_select_harmony:
    alias: "Start Remote activity from input select"
    sequence:
        service: remote.turn_on
        data_template:
          entity_id: remote.living
          activity: >
            {% if is_state("input_select.remote", "Uit") %}
                -1
            {% elif is_state("input_select.remote", "TV kijken") %}
                31061044
            {% elif is_state("input_select.remote", "Chromecast kijken") %}
                31061822
            {% elif is_state("input_select.remote", "Radio luisteren") %}
                31061673
            {% elif is_state("input_select.remote", "Playstation spelen") %}
                31061535
            {% elif is_state("input_select.remote", "Wii spelen") %}
                32004882
            {% endif %}
######################################################
## Automations
######################################################
automation:
  - alias: Media - Remote external update Media Center

    trigger:
      - platform: state
        entity_id: remote.living

    action:
      - delay: '00:00:20'
      - service: input_select.select_option
        data_template:
          entity_id: input_select.remote
          option: >
            {{ states.remote.living.attributes.current_activity }}

  - alias: Media - Remote start activity from input select media center
  
    trigger:
      - platform: state
        entity_id: input_select.remote
  
    action:
      - service: script.turn_on
        entity_id: script.input_select_harmony