######################################################
# @author       :   Mark Bijker
# @package      :   Media
# @description  :   All media players
######################################################


######################################################
## Base and customisations
######################################################
homeassistant:
  
  customize:
    

######################################################
## Components
######################################################
media_player:
  - platform: snapcast
    host: 192.168.1.2
  - platform: mpd
    host: 192.168.1.2

######################################################
## Boolean
######################################################
input_boolean:

######################################################
## Groups
######################################################
group:

######################################################
## Automations
######################################################
automation: