######################################################
## Base and customisations                          ##
######################################################
homeassistant:
  
  customize:
    

######################################################
## Components                                       ##
######################################################
media_player:
  - platform: vlc
    name: RaspBerry PI
    arguments: '--alsa-audio-device=hw:1,0'
######################################################
## Boolean                                          ##
######################################################
input_boolean:

######################################################
## Groups                                           ##
######################################################
group:

######################################################
## Automations                                      ##
######################################################
automation: