######################################################
# @author       :   Mark Bijker
# @package      :   Motion
# @description  :   All motion sensors
######################################################


######################################################
## Base and customisations
######################################################
homeassistant:
  
  customize:
    
    group.motion:
      friendly_name: Beweging
      order: 6
    binary_sensor.motion_shed:
      friendly_name: Schuur
    binary_sensor.alley_1:
      friendly_name: Steeg Links
    binary_sensor.alley_2:
      friendly_name: Steeg Rechts
    binary_sensor.garden:
      friendly_name: Tuin
    binary_sensor.motion_sensor_158d0002270299:
      friendly_name: Hal
######################################################
## Components
######################################################
binary_sensor:
  
  - platform: mqtt
    state_topic: "homeassistant/sensor/schuur/motion"
    name: motion shed
    device_class: motion
  - platform: ffmpeg_motion
    input: !secret camera1
    changes: 30
    name: alley_1
  - platform: ffmpeg_motion
    input: !secret camera2
    changes: 30
    name: alley_2
  - platform: ffmpeg_motion
    input: !secret camera3
    changes: 30
    name: garden
######################################################
## Boolean
######################################################
input_boolean:

######################################################
## Groups
######################################################
group:

  motion:
    entities:
      - binary_sensor.motion_shed

######################################################
## Automations
######################################################
automation:
  
  - alias: lights on in shed after motion
    trigger:
      platform: state
      entity_id: binary_sensor.motion_shed
      to: 'on'
#    condition:
#      - condition: state
#        entity_id: input_boolean.notify_motion
#        state: 'on'
    action:
      service: switch.turn_on
      entity_id: switch.lights_shed_2

  - alias: lights off in shed when motion is off
    trigger:
      platform: state
      entity_id: binary_sensor.motion_shed
      to: 'off'
      for:
        minutes: 5
    action:
      service: switch.turn_off
      entity_id: switch.lights_shed_2

  - alias: Test
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0002270299
      to: 'on'
    action:
      - service: light.turn_on
        entity_id: 
          - light.hue_color_lamp_1
          - light.gateway_light_7811dce13522
      - service: script.speech_main_logic
        data:
          message: "Beweging in de gang."


  - alias: Test2
    trigger:
      platform: state
      entity_id: binary_sensor.motion_sensor_158d0002270299
      to: 'off'
    action:
      - service: light.turn_off
        entity_id: 
          - light.hue_color_lamp_1
          - light.gateway_light_7811dce13522
      - service: script.speech_main_logic
        data:
          message: "Geen beweging meer in de gang."
