homeassistant:
  customize:
    group.motion:
      friendly_name: Beweging
      order: 6
    input_boolean.notify_motion:
      friendly_name: Melding bij beweging bij afwezig
      icon: mdi:bell
    binary_sensor.motion_shed:
      friendly_name: Bewegingsmelder schuur

binary_sensor:
  - platform: mqtt
    state_topic: "homeassistant/sensor/schuur/motion"
    name: motion shed
    device_class: motion

input_boolean:
  notify_motion:
    initial: on
    name: Notify on motion when away

group:
  motion:
    entities:
      - binary_sensor.motion_shed
      - input_boolean.notify_motion