######################################################
# @author       :   Mark Bijker
# @package      :   notify
# @description  :   Notifications automations and booleans
######################################################


######################################################
## Base and customisations
######################################################
homeassistant:
  
  customize:
    group.notify:
      friendly_name: Meldingen
      control: hidden
    input_boolean.notify_diskuse:
      friendly_name: Melding wanneer opslag bijna vol is
      icon: mdi:bell
    input_boolean.notify_everyone_away:
      friendly_name: Melding als iedereen weg is
      icon: mdi:bell
    input_boolean.notify_motion:
      friendly_name: Melding bij beweging bij afwezig
      icon: mdi:bell
    input_boolean.notify_iss:
      friendly_name: Melding wanneer ISS zichtbaar is
      icon: mdi:bell
    input_boolean.notify_offline_device:
      friendly_name: Melding wanneer netwerk apparatuur wegvalt
      icon: mdi:bell
    input_boolean.notify_me:
      friendly_name: Melding naar mij
      icon: mdi:bell
    input_boolean.notify_coming_home:
      friendly_name: Melding als iemand thuis komt
      icon: mdi:bell

######################################################
## Components
######################################################

######################################################
## Boolean
######################################################
input_boolean:
  notify_diskuse:
    initial: on
  notify_everyone_away:
    initial: on
  notify_offline_device:
    initial: on
  notify_motion:
    initial: on
  notify_iss:
    initial: on
  notify_me:
    initial: on
  notify_coming_home:
    initial: on
######################################################
## Groups
######################################################
group:
  notify:
    entities:
      - input_boolean.notify_diskuse
      - input_boolean.notify_everyone_away
      - input_boolean.notify_iss
      - input_boolean.notify_motion
      - input_boolean.notify_offline_device
      - input_boolean.notify_me
      - input_boolean.notify_coming_home

######################################################
## Automations
######################################################
automation:

######################################################
## Scripts
######################################################
script:
