######################################################
## Base and customisations                          ##
######################################################
homeassistant:
  
  customize:
    group.performance:
      friendly_name: Systeem monitor
    sensor.disk_free_:
      friendly_name: Opslagruimte beschikbaar
    sensor.disk_use_:
      friendly_name: Opslagruimte gebruikt
    sensor.last_boot:
      friendly_name: Laatste herstart
    sensor.memory_use:
      friendly_name: Geheugen gebruikt
    sensor.network_in_eth0:
      friendly_name: Inkomende data (eth0)
    sensor.network_out_eth0:
      friendly_name: Uitgaande data (eth0)
    sensor.processor_use:
      friendly_name: Processor gebruik
    input_boolean.notify_diskuse:
      friendly_name: Melding wanneer opslag bijna vol is

    

######################################################
## Components                                       ##
######################################################
sensor:
  - platform: speedtest
    minute:
      - 0
      - 30
    monitored_conditions:
      - ping
      - download
      - upload
  - platform: systemmonitor
    resources:
      - type: memory_use
      - type: processor_use   
      - type: disk_use
        arg: /
      - type: disk_free
        arg: /
      - type: last_boot
      - type: network_in
        arg: eth0
      - type: network_out
        arg: eth0
######################################################
## Boolean                                          ##
######################################################
input_boolean:
  notify_diskuse:
    initial: off
######################################################
## Groups                                           ##
######################################################
group:
  performance:
    entities: 
      - sensor.speedtest_ping
      - sensor.speedtest_upload
      - sensor.speedtest_download
      - sensor.processor_use
      - sensor.memory_use
      - sensor.disk_free_
      - sensor.disk_use_
      - sensor.network_in_eth0
      - sensor.network_out_eth0
      - sensor.last_boot
      - input_boolean.notify_diskuse
######################################################
## Automations                                      ##
######################################################
automation:
