homeassistant:
  customize:

    group.presence:
      order: 1

    device_tracker.mbijker_s7mark:
      friendly_name: Mark
      gravatar: 'mbijker84@gmail.com'
    device_tracker.miran000siphone:
      friendly_name: Miranda
      entity_picture: /local/mallika.jpg

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200
    waypoints: True

group:
  presence:
    control: hidden
    entities:
      - device_tracker.mbijker_s7mark
      - device_tracker.miran000siphone