######################################################
# @author       :   Mark Bijker
# @package      :   
# @description  :   
######################################################


######################################################
## Base and customisations
######################################################
homeassistant:
  customize:
    group.printer:
      friendly_name: Printer
    sensor.samsung_m2020_series_192168169_toner_black:
      friendly_name: Toner
    sensor.samsung_m2020_series_192168169_tray_1:
      friendly_name: Papier

######################################################
## Components
######################################################

######################################################
## Boolean
######################################################
input_boolean:

######################################################
## Groups
######################################################
group:
  printer:
    entities:
#      - sensor.samsung_m2020_series_192168169_output_tray_0
      - sensor.samsung_m2020_series_192168169_toner_black
      - sensor.samsung_m2020_series_192168169_tray_1
######################################################
## Automations
######################################################
automation:

######################################################
## Scripts
######################################################
script:
