######################################################
# @author       :   Mark Bijker
# @package      :   Solar
# @description  :   Monitoring and interacting with my  solar panel system
######################################################


######################################################
## Base and customisations
######################################################
homeassistant:
  customize:
    

######################################################
## Components
######################################################
sensor:
  - platform: pvoutput
    system_id: !secret pvoutput_sysid
    api_key: !secret pvoutput_api_key
    scan_interval: 120
######################################################
## Boolean
######################################################
input_boolean:

######################################################
## Groups
######################################################
group:

######################################################
## Automations
######################################################
automation:

######################################################
## Scripts
######################################################
script:
