######################################################
# @author       :   Mark Bijker
# @package      :   
# @description  :   
######################################################


######################################################
## Base and customisations
######################################################
homeassistant:
  
  customize:
    

######################################################
## Components
######################################################

######################################################
## Boolean
######################################################
input_boolean:

######################################################
## Groups
######################################################
group:

######################################################
## Automations
######################################################
automation:

######################################################
## Scripts
######################################################
script:
