######################################################
# @author       :   Mark Bijker
# @package      :   Termperature
# @description  :   All temperature sensors
######################################################


######################################################
## Base and customisations
######################################################
homeassistant:
  customize:
    group.temperature:
      friendly_name: Temperatuur
    sensor.temperature_shed:
      friendly_name: Schuur
      icon: mdi:thermometer

######################################################
## Components
######################################################
sensor:
  - platform: mqtt
    state_topic: "homeassistant/sensor/schuur/temperature"
    unit_of_measurement: "°C"
    name: temperature_shed

######################################################
## Boolean
######################################################
input_boolean:

######################################################
## Groups
######################################################
group:
  temperature:
    entities:
      - sensor.temperature_shed

######################################################
## Automations
######################################################
automation: