######################################################
# @author       :   Mark Bijker
# @package      :   Time
# @description  :   Time and date sensors
######################################################


######################################################
## Base and customisations
######################################################
homeassistant:
  customize:
    group.time:
      order: 0
      friendly_name: Klok
    sensor.time:
      friendly_name: Tijd
    sensor.date:
      friendly_name: Datum
    sun.sun:
      friendly_name: Zon    

######################################################
## Components
######################################################
sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'

######################################################
## Boolean
######################################################
input_boolean:

######################################################
## Groups
######################################################
group:
  time:
    entities: 
      - sensor.time
      - sensor.date
      - sun.sun

######################################################
## Automations
######################################################
automation:
  - alias: "Zon onder"
    trigger:
      platform: sun
      event: sunset
    action:
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.daymode
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.nightmode
  - alias: "Zon op"
    trigger:
      platform: sun
      event: sunrise
    action:
      - service: input_boolean.turn_on
        data:
          entity_id: input_boolean.daymode
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.nightmode
  