######################################################
# @author       :   Mark Bijker
# @package      :   Time
# @description  :   Time and date sensors
######################################################


######################################################
## Base and customisations
######################################################
homeassistant:
  customize:
    group.time:
      order: 0
      friendly_name: Klok
    sensor.time:
      friendly_name: Tijd
    sensor.date:
      friendly_name: Datum
    sun.sun:
      friendly_name: Zon    

######################################################
## Components
######################################################
sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'

######################################################
## Boolean
######################################################
input_boolean:

######################################################
## Groups
######################################################
group:
  time:
    entities: 
      - sensor.time
      - sensor.date
      - sun.sun

######################################################
## Automations
######################################################
automation: