######################################################
# @author       :   Mark Bijker
# @package      :   
# @description  :   
######################################################


######################################################
## Base and customisations
######################################################
homeassistant:
  customize:
    

######################################################
## Components
######################################################
xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - key: 2wgu1r4nkivzl0q4


######################################################
## Boolean
######################################################
input_boolean:

######################################################
## Groups
######################################################
group:

######################################################
## Automations
######################################################
automation:
  - alias: Going to bed
    trigger:
      platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d000128b24a
        click_type: single
    condition:
      condition: time
      after: "21:00:00"
    action:
      - service: script.to_bed
  
  - alias: Dinner time
    trigger:
      platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d000128b24a
        click_type: single
    condition:
      condition: time
      after: "16:00:00"
      before: "20:00:00"
    action:
      - service: script.dinner_time