######################################################
# @author       :   Mark Bijker
# @package      :   
# @description  :   
######################################################


######################################################
## Base and customisations
######################################################
homeassistant:
  customize:
    

######################################################
## Components
######################################################
xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: xjn6rpm7fv3vrg69
######################################################
## Boolean
######################################################
input_boolean:

######################################################
## Groups
######################################################
group:

######################################################
## Automations
######################################################
automation:

######################################################
## Scripts
######################################################
script:
